Revert "Update webhook secret"
This reverts commit 79b26a283fb24c8b993f6fdac57e488da82694d6.

diff --git a/.github/workflows/cargo-toml-lint.yml b/.github/workflows/cargo-toml-lint.yml
--- a/.github/workflows/cargo-toml-lint.yml
+++ b/.github/workflows/cargo-toml-lint.yml
@@ -30,7 +30,9 @@ jobs:
           version: 0.1
 
       - name: Run Cargo.toml Linter
-        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint
+        # run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint
+        # failure test
+        run: exit 1
 
   notify-slack-action:
     uses: FuelLabs/github-actions/.github/workflows/notify-slack-action.yml@elliot/notify-slack-action
